apiVersion: v1
kind: Pod
metadata:
  name: web-server-cloud-app
  labels:
   app: webserver-cloud-app
   region: IN
   rack: r1
   version: "1.1"
spec:
  containers:
    - name: web-server-cloud-app
      image: paulinomreyes/cloud-app-image
      ports:
      - containerPort: 8080
