apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver-rc
spec:
  replicas: 3
  selector:
    app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
        version: "1.1"
    spec:
      containers:
      - name: web-server-cloud-app
        image: paulinomreyes/cloud-app-image
        ports:
        - containerPort: 8080
