apiVersion: v1
kind: Service
metadata:
 name: cloud-app-service
 labels:
   app: cloud-app-service-label
spec:
 type: NodePort
 ports:
 - port: 8080
   nodePort: 30001
   protocol: TCP
 selector:
   version: "1.1"
